name: RemoteTerminal

options:
  bundleIdPrefix: com.remoteterminal
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    SUPPORTS_MACCATALYST: false
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}

packages:
  swift-nio-ssh:
    url: https://github.com/apple/swift-nio-ssh.git
    from: "0.8.0"

targets:
  RemoteTerminal:
    type: application
    platform: iOS
    sources:
      - path: RemoteTerminal
        excludes:
          - "**/.DS_Store"
      - path: RemoteTerminal/Assets.xcassets
      - path: RemoteTerminal/Resources
    dependencies:
      - package: swift-nio-ssh
        product: NIOSSH
    settings:
      base:
        INFOPLIST_FILE: RemoteTerminal/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.remoteterminal.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: true
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "Apple Development"
        Release:
          CODE_SIGN_IDENTITY: "Apple Distribution"
    preBuildScripts:
      - name: "Check SwiftLint"
        script: |
          if which swiftlint > /dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
        runOnlyWhenInstalling: false
